# Generated by Django 4.1.7 on 2023-04-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_awards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='awards',
        ),
    ]
